- name: run varnish
  action: service name=${varnish_service_name} state=restarted
- name: restart varnish
  action: service name=${varnish_service_name} state=restarted
- name: reload varnish
  action: service name=${varnish_service_name} state=reloaded
